# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf69410e9506294422e29d2330b251a3b850b2dfd6a7280b4fa3b53ac40a9fe7aa59ea6cca7a1eea134ed536cc266ec2adcf1a31225daed94fdbd409bf7a24d6

test:
  secret_key_base: 2d62292037b6f2b8a55d9de94c0e7da8c01198dc34bf1291d29d2f81903f62598e8565c98910918af0ec5209801ac86fa75fbb03efc6fafde337bdbfab83db84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
